VENDOR_PATH := vendor/evercoss/cross82_3821


PRODUCT_COPY_FILES += \
	$(VENDOR_PATH)/lib/egl/libEGL_mali.so:system/lib/egl/libEGL_mali.so \
	$(VENDOR_PATH)/lib/egl/libGLESv1_CM_mali.so:system/lib/egl/libGLESv1_CM_mali.so \
	$(VENDOR_PATH)/lib/egl/libGLESv2_mali.so:system/lib/egl/libGLESv2_mali.so \
	$(VENDOR_PATH)/lib/hw/hwcomposer.mt6582.so:system/lib/hw/hwcomposer.mt6582.so \
	$(VENDOR_PATH)/lib/hw/gralloc.mt6582.so:system/lib/hw/gralloc.mt6582.so \
	$(VENDOR_PATH)/lib/libMali.so:system/lib/libMali.so \
	$(VENDOR_PATH)/lib/libmtk_mali_user.so:system/lib/libmtk_mali_user.so \
	$(VENDOR_PATH)/lib/libgralloc_extra.so:system/lib/libgralloc_extra.so \
	$(VENDOR_PATH)/lib/drm/libdrmmtkplugin.so:system/lib/drm/libdrmmtkplugin.so \
	$(VENDOR_PATH)/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
	$(VENDOR_PATH)/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
	$(VENDOR_PATH)/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
	$(VENDOR_PATH)/vendor/lib/hw/audio.a2dp.blueangel.so:system/vendor/lib/hw/audio.a2dp.blueangel.so \
	$(VENDOR_PATH)/vendor/lib/hw/bluetooth.blueangel.so:system/vendor/lib/hw/bluetooth.blueangel.so \
	$(VENDOR_PATH)/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
	$(VENDOR_PATH)/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
	$(VENDOR_PATH)/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7 \
	$(VENDOR_PATH)/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32.bin \
	$(VENDOR_PATH)/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32.bin \
	$(VENDOR_PATH)/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-2.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-2.bin \
	$(VENDOR_PATH)/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6 \
	$(VENDOR_PATH)/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rp30-ri30.5-v24.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rp30-ri30.5-v24.bin \
	$(VENDOR_PATH)/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-r0-ri30.4a-v24.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-r0-ri30.4a-v24.bin \
	$(VENDOR_PATH)/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rn30-ri30.5-v24.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rn30-ri30.5-v24.bin \
	$(VENDOR_PATH)/vendor/pittpatt/models/recognition:system/vendor/pittpatt/models/recognition \
	$(VENDOR_PATH)/vendor/pittpatt/models/recognition/face.face.y0-y0-22-b-N.bin:system/vendor/pittpatt/models/recognition/face.face.y0-y0-22-b-N.bin \
	$(VENDOR_PATH)/vendor/operator/app/CleanMaster.apk:system/vendor/operator/app/CleanMaster.apk \
	$(VENDOR_PATH)/vendor/operator/app/DSB.apk:system/vendor/operator/app/DSB.apk \
	$(VENDOR_PATH)/vendor/operator/app/CrossCompass.apk:system/vendor/operator/app/CrossCompass.apk \
	$(VENDOR_PATH)/vendor/operator/app/Velvet.apk:system/vendor/operator/app/Velvet.apk \
	$(VENDOR_PATH)/vendor/operator/app/ubox.apk:system/vendor/operator/app/ubox.apk \
	$(VENDOR_PATH)/vendor/operator/app/FaceBook.apk:system/vendor/operator/app/FaceBook.apk \
	$(VENDOR_PATH)/vendor/operator/app/Bbm.apk:system/vendor/operator/app/Bbm.apk \
	$(VENDOR_PATH)/etc/fmr/mt6627_fm_cust.cfg:system/etc/fmr/mt6627_fm_cust.cfg \
	$(VENDOR_PATH)/etc/mtk_omx_core.cfg:system/etc/mtk_omx_core.cfg \
	$(VENDOR_PATH)/etc/permissions/android.hardware.touchscreen.xml:system/etc/permissions/android.hardware.touchscreen.xml \
	$(VENDOR_PATH)/etc/permissions/android.hardware.faketouch.xml:system/etc/permissions/android.hardware.faketouch.xml \
	$(VENDOR_PATH)/etc/permissions/com.android.location.provider.xml:system/etc/permissions/com.android.location.provider.xml \
	$(VENDOR_PATH)/etc/permissions/android.hardware.camera.xml:system/etc/permissions/android.hardware.camera.xml \
	$(VENDOR_PATH)/etc/permissions/android.software.sip.xml:system/etc/permissions/android.software.sip.xml \
	$(VENDOR_PATH)/etc/permissions/android.hardware.sensor.light.xml:system/etc/permissions/android.hardware.sensor.light.xml \
	$(VENDOR_PATH)/etc/permissions/android.hardware.sensor.compass.xml:system/etc/permissions/android.hardware.sensor.compass.xml \
	$(VENDOR_PATH)/etc/permissions/com.android.media.remotedisplay.xml:system/etc/permissions/com.android.media.remotedisplay.xml \
	$(VENDOR_PATH)/etc/permissions/android.hardware.touchscreen.multitouch.distinct.xml:system/etc/permissions/android.hardware.touchscreen.multitouch.distinct.xml \
	$(VENDOR_PATH)/etc/permissions/features.xml:system/etc/permissions/features.xml \
	$(VENDOR_PATH)/etc/permissions/com.mediatek.effect.xml:system/etc/permissions/com.mediatek.effect.xml \
	$(VENDOR_PATH)/etc/permissions/handheld_core_hardware.xml:system/etc/permissions/handheld_core_hardware.xml \
	$(VENDOR_PATH)/etc/permissions/com.google.widevine.software.drm.xml:system/etc/permissions/com.google.widevine.software.drm.xml \
	$(VENDOR_PATH)/etc/permissions/android.software.live_wallpaper.xml:system/etc/permissions/android.software.live_wallpaper.xml \
	$(VENDOR_PATH)/etc/permissions/android.hardware.usb.accessory.xml:system/etc/permissions/android.hardware.usb.accessory.xml \
	$(VENDOR_PATH)/etc/permissions/android.hardware.telephony.gsm.xml:system/etc/permissions/android.hardware.telephony.gsm.xml \
	$(VENDOR_PATH)/etc/permissions/google.xml:system/etc/permissions/google.xml \
	$(VENDOR_PATH)/etc/permissions/android.hardware.bluetooth.xml:system/etc/permissions/android.hardware.bluetooth.xml \
	$(VENDOR_PATH)/etc/permissions/android.hardware.bluetooth_le.xml:system/etc/permissions/android.hardware.bluetooth_le.xml \
	$(VENDOR_PATH)/etc/permissions/platform.xml:system/etc/permissions/platform.xml \
	$(VENDOR_PATH)/etc/permissions/android.hardware.touchscreen.multitouch.xml:system/etc/permissions/android.hardware.touchscreen.multitouch.xml \
	$(VENDOR_PATH)/etc/permissions/android.hardware.location.gps.xml:system/etc/permissions/android.hardware.location.gps.xml \
	$(VENDOR_PATH)/etc/permissions/android.hardware.sensor.accelerometer.xml:system/etc/permissions/android.hardware.sensor.accelerometer.xml \
	$(VENDOR_PATH)/etc/permissions/android.hardware.touchscreen.multitouch.jazzhand.xml:system/etc/permissions/android.hardware.touchscreen.multitouch.jazzhand.xml \
	$(VENDOR_PATH)/etc/permissions/android.hardware.sensor.proximity.xml:system/etc/permissions/android.hardware.sensor.proximity.xml \
	$(VENDOR_PATH)/etc/permissions/media_codecs.xml:system/etc/permissions/media_codecs.xml \
	$(VENDOR_PATH)/etc/permissions/com.google.android.maps.xml:system/etc/permissions/com.google.android.maps.xml \
	$(VENDOR_PATH)/etc/permissions/android.software.sip.voip.xml:system/etc/permissions/android.software.sip.voip.xml \
	$(VENDOR_PATH)/etc/permissions/android.hardware.wifi.direct.xml:system/etc/permissions/android.hardware.wifi.direct.xml \
	$(VENDOR_PATH)/etc/permissions/android.hardware.microphone.xml:system/etc/permissions/android.hardware.microphone.xml \
	$(VENDOR_PATH)/etc/permissions/com.google.android.media.effects.xml:system/etc/permissions/com.google.android.media.effects.xml \
	$(VENDOR_PATH)/etc/permissions/android.hardware.wifi.xml:system/etc/permissions/android.hardware.wifi.xml \
	$(VENDOR_PATH)/etc/mddb/BPLGUInfoCustomAppSrcP_MT6582_S00_MOLY_WR8_W1315_MD_WG_MP_V35_P5_1_wg_n:system/etc/mddb/BPLGUInfoCustomAppSrcP_MT6582_S00_MOLY_WR8_W1315_MD_WG_MP_V35_P5_1_wg_n \
	$(VENDOR_PATH)/etc/firmware/mt6572_82_patch_e1_1_hdr.bin:system/etc/firmware/mt6572_82_patch_e1_1_hdr.bin \
	$(VENDOR_PATH)/etc/firmware/WMT_SOC.cfg:system/etc/firmware/WMT_SOC.cfg \
	$(VENDOR_PATH)/etc/firmware/WIFI_RAM_CODE:system/etc/firmware/WIFI_RAM_CODE \
	$(VENDOR_PATH)/etc/firmware/mt6572_82_patch_e1_0_hdr.bin:system/etc/firmware/mt6572_82_patch_e1_0_hdr.bin \
	$(VENDOR_PATH)/etc/firmware/WIFI_RAM_CODE_MT6582:system/etc/firmware/WIFI_RAM_CODE_MT6582 \
	$(VENDOR_PATH)/etc/firmware/S_ANDRO_SFL.ini:system/etc/firmware/S_ANDRO_SFL.ini \
	$(VENDOR_PATH)/etc/firmware/mt6627/mt6627_fm_v5_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v5_coeff.bin \
	$(VENDOR_PATH)/etc/firmware/mt6627/mt6627_fm_v5_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v5_patch.bin \
	$(VENDOR_PATH)/etc/firmware/mt6627/mt6627_fm_v3_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v3_coeff.bin \
	$(VENDOR_PATH)/etc/firmware/mt6627/mt6627_fm_v4_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v4_patch.bin \
	$(VENDOR_PATH)/etc/firmware/mt6627/mt6627_fm_v3_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v3_patch.bin \
	$(VENDOR_PATH)/etc/firmware/mt6627/mt6627_fm_v2_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v2_patch.bin \
	$(VENDOR_PATH)/etc/firmware/mt6627/mt6627_fm_v4_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v4_coeff.bin \
	$(VENDOR_PATH)/etc/firmware/mt6627/mt6627_fm_v1_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v1_patch.bin \
	$(VENDOR_PATH)/etc/firmware/mt6627/mt6627_fm_v1_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v1_coeff.bin \
	$(VENDOR_PATH)/etc/firmware/mt6627/mt6627_fm_v2_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v2_coeff.bin \
	$(VENDOR_PATH)/etc/firmware/catcher_filter_1_wg_n.bin:system/etc/firmware/catcher_filter_1_wg_n.bin \
	$(VENDOR_PATH)/etc/firmware/modem_1_wg_n.img:system/etc/firmware/modem_1_wg_n.img \
	$(VENDOR_PATH)/etc/firmware/WIFI_RAM_CODE_MT6628:system/etc/firmware/WIFI_RAM_CODE_MT6628 \
	$(VENDOR_PATH)/etc/firmware/WIFI_RAM_CODE_E6:system/etc/firmware/WIFI_RAM_CODE_E6

